{
 "title": "App Services",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource group",
    "query": {}
   },
   {
    "name": "resource",
    "label": "App Service ",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuTime",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AppConnections",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Current Assemblies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CurrentAssemblies",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Handle & Thread Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Handles",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Threads",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "App Domains",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalAppDomains",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalAppDomainsUnloaded",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Gen0Collections",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Gen1Collections",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Gen2Collections",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http101",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http2xx",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http3xx",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http401",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http403",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http404",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http404",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http406",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http4xx",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Data In/Out",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "IO Read/Write",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IoReadBytesPerSecond",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IoWriteBytesPerSecond",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IoReadOperationsPerSecond",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IoWriteOperationsPerSecond",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "Microsoft.Web/sites", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}