{
 "title": "App Service Plans",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource group",
    "query": {}
   },
   {
    "name": "resource",
    "label": "App Service Plan",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "TCP Time wait",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TcpTimeWait",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "TCP Established",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TcpEstablished",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "TCP syn sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TcpSynSent",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "TCP syn received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TcpSynReceived",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "TCP Fin Wait 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TcpFinWait1",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "TCP Fin Wait 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TcpFinWait2",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Socket Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SocketInboundAll",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SocketOutboundAll",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SocketOutboundEstablished",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SocketLoopback",
      "metricNamespace": "microsoft.web/serverfarms",
      "resources": [
       { "metricNamespace": "Microsoft.Web/serverFarms", "resourceGroup": "$rg", "resourceName": "$resource", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}