{
 "title": "Application Gateways",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource group",
    "query": {}
   },
   {
    "name": "resource",
    "label": "Application Gateway",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Application Gateway Tooltime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ApplicationGatewayTotalTime",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Current Capacity Units",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CapacityUnits",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Current compute Units",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ComputeUnits",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CurrentConnections",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Request Metrics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FailedRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AvgRequestCountPerHealthyHost",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ResponseStatus",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendResponseStatus",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Throughput",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Bytes sent/received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UnhealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}