{
 "title": "Azure API Management",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ns_apim",
    "label": "Namespace",
    "query": "Microsoft.ApiManagement/service"
   },
   {
    "name": "resource_apim",
    "label": "API Management service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Security Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UnauthorizedRequests",
      "metricNamespace": "microsoft.apimanagement/service",
      "resources": [
       {
        "metricNamespace": "Microsoft.ApiManagement/service",
        "resourceGroup": "$rg",
        "resourceName": "$resource_apim",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendDuration",
      "metricNamespace": "microsoft.apimanagement/service",
      "resources": [
       {
        "metricNamespace": "Microsoft.ApiManagement/service",
        "resourceGroup": "$rg",
        "resourceName": "$resource_apim",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Gateway Traffic",
   "type": "stat",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.apimanagement/service",
      "resources": [
       {
        "metricNamespace": "Microsoft.ApiManagement/service",
        "resourceGroup": "$rg",
        "resourceName": "$resource_apim",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulRequests",
      "metricNamespace": "microsoft.apimanagement/service",
      "resources": [
       {
        "metricNamespace": "Microsoft.ApiManagement/service",
        "resourceGroup": "$rg",
        "resourceName": "$resource_apim",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FailedRequests",
      "metricNamespace": "microsoft.apimanagement/service",
      "resources": [
       {
        "metricNamespace": "Microsoft.ApiManagement/service",
        "resourceGroup": "$rg",
        "resourceName": "$resource_apim",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current Capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Capacity",
      "metricNamespace": "$ns_apim/$resource_apim",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 19 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Capacity",
      "metricNamespace": "$ns_apim/$resource_apim",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Requests (Failed & Successful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Success",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "GatewayResponseCode",
        "filters": [
         "0",
         "200"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "$ns_apim/$resource_apim",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Fail",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "GatewayResponseCode",
        "filters": [
         "0",
         "200"
        ],
        "operator": "ne"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "$ns_apim/$resource_apim",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Duration of Backend Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendDuration",
      "metricNamespace": "$ns_apim/$resource_apim",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "GatewayResponseCode",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "$ns_apim/$resource_apim",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns_apim/$resource_apim",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}