{
 "title": "Azure SQL Databases",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "query": {}
   },
   {
    "name": "rg",
    "query": {}
   },
   {
    "name": "server",
    "query": {}
   },
   {
    "name": "resource",
    "label": "Database",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "DTU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/databases",
      "dimensionFilters": [],
      "metricName": "dtu_consumption_percent",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/databases",
      "dimensionFilters": [],
      "metricName": "dtu_limit",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.sql/servers/databases",
      "dimensionFilters": [],
      "metricName": "dtu_used",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Query Performance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "physical_data_read_percent",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "log_write_percent",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "deadlock",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connection_successful",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Data",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "physical_data_read_percent",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "allocated_data_storage",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connection_failed",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connection_failed_user_error",
      "metricNamespace": "microsoft.sql/servers/databases",
      "resources": [
       {
        "metricNamespace": "Microsoft.Sql/servers/databases",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}