{
 "title": "Firewalls",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource group",
    "query": {}
   },
   {
    "name": "resource",
    "label": "Firewall",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Throughput",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 16, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "NetworkRuleHit",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ApplicationRuleHit",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FirewallHealth",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FirewallLatencyPng",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Data Processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DataProcessed",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Snap Port Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SNATPortUtilization",
      "metricNamespace": "microsoft.network/azurefirewalls",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/azureFirewalls",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}