{
 "title": "Service Bus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource group",
    "query": {}
   },
   {
    "name": "resource",
    "label": "Service Bus",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Size",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveConnections",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CompleteMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AbandonMessage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Checkpoint Operations Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "PendingCheckpointOperationCount",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Send Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerSendLatency",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throttled Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "NamespaceCpuUsage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "NamespaceMemoryUsage",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}