{
 "title": "Virtual Machine",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "Sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource group",
    "query": {}
   },
   {
    "name": "VM",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Memory Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VmAvailabilityMetric",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "OS Disk Read & Write Bytes/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Read Bytes/sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Write Bytes/sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Temp Disk Read & Write Bytes/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Temp Disk Read Bytes/sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Temp Disk Write Bytes/sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Latency",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "CPU Credits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CPU Credits Remaining",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CPU Credits Consumed",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Inbound/Outbound Flows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Inbound Flows",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Outbound Flows",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Inbound Flows Maximum Creation Rate",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Outbound Flows Maximum Creation Rate",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "Heartbeat\r\n| where Resource ==\"$VM\"\r\n| summarize LastSeen = max(TimeGenerated)\r\n| extend Uptime = now() - LastSeen\r\n| project Uptime\r\n",
      "resources": [ "/subscriptions/$Sub" ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Agent Health",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "Heartbeat\r\n| where Resource == \"$VM\"\r\n| summarize LastHeartbeat = max(TimeGenerated) by Computer\r\n| extend AgentStatus = iff(now() - LastHeartbeat > 1h, \"Unhealthy\", \"Healthy\")\r\n| project Computer, LastHeartbeat, AgentStatus",
      "resources": [ "/subscriptions/$Sub" ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  { "title": "OS Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Queue Depth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Queue Depth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Latency",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Target IOPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Target IOPS",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Target Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Target Bandwidth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "IOPS Consumed Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk IOPS Consumed Percentage",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Max Brust Bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Max Burst Bandwidth",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  },
  {
   "title": "Max Brust IOPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Max Burst IOPS",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$Sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Sub"
    }
   ]
  }
 ]
}